# vars
CC = g++
LL = g++
EXE = testRNAdesign
ARGS = --log_level=test_suite
LIBS = -lstdc++ -I../src/
LDFLAGS = -lboost_unit_test_framework
DEFS =
WARN = -Wall
OPTI = -g
STD  = -std=c++11
CCFLAGS = $(WARN) $(STD) $(OPTI) $(DEFS) $(LIBS)
CTSRC = main.cc test_pathcoloring.cc test_graphcoloring.cc test_decompose.cc test_parsestruct.cc test_random_gen.cc
CPSRC = ../common.cc ../graphcommon.cc ../printgraph.cc ../decompose.cc ../treestatistics.cc ../parsestruct.cc ../pathcoloring.cc ../graphcoloring.cc
CSRC = $(CTSRC) $(CPSRC)
COBJ = $(CSRC:.cc=.o)
# rules
all: $(EXE)
	@echo testRNAdesign has been compiled
$(EXE): $(COBJ)
	$(CC) $(CCFLAGS) $(LDFLAGS) -o $(EXE) $(COBJ) 
.cc.o:
	$(CC) -c $(CCFLAGS) $< -o $@
run:	$(EXE)
	./$(EXE) $(ARGS)
clean:
	rm -f $(COBJ)
	rm -f $(EXE)
	rm -f *~ */*~
PHONY: clean
