# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package RNAdesign;
use base qw(Exporter);
use base qw(DynaLoader);
package RNAdesignc;
bootstrap RNAdesign;
package RNAdesign;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package RNAdesign;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package RNAdesign;

*initialize_library = *RNAdesignc::initialize_library;

############# Class : RNAdesign::IntVector ##############

package RNAdesign::IntVector;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( RNAdesign );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = RNAdesignc::new_IntVector(@_);
    bless $self, $pkg if defined($self);
}

*size = *RNAdesignc::IntVector_size;
*empty = *RNAdesignc::IntVector_empty;
*clear = *RNAdesignc::IntVector_clear;
*push = *RNAdesignc::IntVector_push;
*pop = *RNAdesignc::IntVector_pop;
*get = *RNAdesignc::IntVector_get;
*set = *RNAdesignc::IntVector_set;
*getvec = *RNAdesignc::IntVector_getvec;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        RNAdesignc::delete_IntVector($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : RNAdesign::Map_Int_IntVector ##############

package RNAdesign::Map_Int_IntVector;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( RNAdesign );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = RNAdesignc::new_Map_Int_IntVector(@_);
    bless $self, $pkg if defined($self);
}

*SCALAR = *RNAdesignc::Map_Int_IntVector_SCALAR;
*empty = *RNAdesignc::Map_Int_IntVector_empty;
*CLEAR = *RNAdesignc::Map_Int_IntVector_CLEAR;
*FETCH = *RNAdesignc::Map_Int_IntVector_FETCH;
*STORE = *RNAdesignc::Map_Int_IntVector_STORE;
*DELETE = *RNAdesignc::Map_Int_IntVector_DELETE;
*EXISTS = *RNAdesignc::Map_Int_IntVector_EXISTS;
*TIEHASH = *RNAdesignc::Map_Int_IntVector_TIEHASH;
*FIRSTKEY = *RNAdesignc::Map_Int_IntVector_FIRSTKEY;
*NEXTKEY = *RNAdesignc::Map_Int_IntVector_NEXTKEY;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        RNAdesignc::delete_Map_Int_IntVector($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : RNAdesign::DependencyGraphMT ##############

package RNAdesign::DependencyGraphMT;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( RNAdesign );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = RNAdesignc::new_DependencyGraphMT(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        RNAdesignc::delete_DependencyGraphMT($self);
        delete $OWNER{$self};
    }
}

*get_sequence = *RNAdesignc::DependencyGraphMT_get_sequence;
*set_sequence = *RNAdesignc::DependencyGraphMT_set_sequence;
*mutate_local = *RNAdesignc::DependencyGraphMT_mutate_local;
*mutate_global = *RNAdesignc::DependencyGraphMT_mutate_global;
*mutate = *RNAdesignc::DependencyGraphMT_mutate;
*number_of_sequences = *RNAdesignc::DependencyGraphMT_number_of_sequences;
*connected_components = *RNAdesignc::DependencyGraphMT_connected_components;
*special_vertices = *RNAdesignc::DependencyGraphMT_special_vertices;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package RNAdesign;

1;
